name: Deploy resume

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install resume CLI
      run: npm i -g resume-cli
    - name: Compile resume to HTML
      run: resume export index.html
    - name: Compile resume to PDF
      run: resume export resume.pdf
    - uses: EndBug/add-and-commit@v4
      with:
        add: resume.pdf index.html
        author_name: Nour Haridy
        author_email: nourharidy@gmail.com
        force: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
